spring:
  datasource:
     url: jdbc:mysql://180.76.179.32:3306/plp
     username: root
     password: "@budejietuo0205"
     driver-class-name: com.mysql.jdbc.Driver
     hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  redis:
        #数据库索引
        database: 0
        host: 180.76.179.32
        port: 6379
        password : 
        jedis:
          pool:
            #最大连接数
            max-active: 8
            #最大阻塞等待时间(负数表示没限制)
            max-wait: -1
            #最大空闲
            max-idle: 8
            #最小空闲
            min-idle: 0
        #连接超时时间
        timeout: 50000
